export enum RoomType {
  ROOM_IMAX = 'ROOM_IMAX',
  ROOM_4DX = 'ROOM_4DX',
  ROOM_DBOX = 'ROOM_DBOX',
  ROOM_XD = 'ROOM_XD',
  ROOM_CINEPIC = 'ROOM_CINEPIC',
  ROOM_VIP = 'ROOM_VIP',
  ROOM_PRIME = 'ROOM_PRIME',
}